version: '3'

networks:
  common:

volumes:
  mongo-db:

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3000
    networks:
      - common
    depends_on:
      - mongo

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 3000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - common

  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=devuser
      - MONGO_INITDB_ROOT_PASSWORD=gcsvn123
    volumes:
      - mongo-db:/data/db
    networks:
      - common

  redis:
    container_name: redis
    image: redis
    networks:
      - common
