version: '3'

services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=devuser
      - MONGO_PASSWORD=gcsvn123
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=devuser
      - MONGO_INITDB_ROOT_PASSWORD=gcsvn123
