version: '3'

networks:
  common:

volumes:
  mongo-db:

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3300:3000
    environment:
      - PORT=3000
    networks:
      - common
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=devuser
      - MONGO_INITDB_ROOT_PASSWORD=gcsvn123
    volumes:
      - mongo-db:/data/db
    networks:
      - common

  redis:
    container_name: redis
    image: redis
    networks:
      - common
